### PR TITLE
Add cargo-clippy options

### PR DESCRIPTION
**Pull request by oldgalileo**

### CODE REVIEW

**Comment by messense** [comment]
```
$ cargo clippy --help
Checks a package to catch common mistakes and improve your Rust code.

Usage:
    cargo clippy [options] [--] [<opts>...]

Common options:
    --no-deps                Run Clippy only on the given crate, without linting the dependencies
    --fix                    Automatically apply lint suggestions. This flag implies `--no-deps`
    -h, --help               Print this message
    -V, --version            Print version info and exit
    --explain LINT           Print the documentation for a given lint

Other options are the same as `cargo check`.
```

This doesn't cover all others options supported by `cargo check`, perhaps it's better to add a `cargo check` options first, then `cargo clippy` options can be built on top of it.

**Comment by oldgalileo** [comment]
@messense added `cargo check` alongside its options, with deduplication out of `cargo run` as well as `cargo clippy`

**Comment by messense** [comment]
There is a test failure:

```
test test::tests::verify_cli ... FAILED

failures:

---- test::tests::verify_cli stdout ----
thread 'test::tests::verify_cli' panicked at 'Command cargo-options: Argument names must be unique, but 'future_incompat_report' is in use by more than one argument or group', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-4.0.28/src/builder/debug_asserts.rs:95:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by messense** [comment]
I'll merge and fix it.

**Comment by messense** [comment]
> with deduplication out of `cargo run` as well as `cargo clippy`

I'll have to revert this part because it make the cli help wrong for `cargo test`.

image

**Comment by messense** [comment]
https://github.com/messense/cargo-options/pull/6

**Pull request merged**
